### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Ingvarr71** [AquariOS/manifest#9]
[ 54% 431/784] //frameworks/base/services/core:services.core.unboosted javac [common]
FAILED: /home/iodine71/aq/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/services.core.unboosted.jar 
rm -rf "/home/iodine71/aq/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes" "/home/iodine71/aq/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/anno" "/home/iodine71/aq/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars" && mkdir -p "/home/iodine71/aq/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes" "/home/iodine71/aq/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/anno" "/home/iodine71/aq/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars" && /home/iodine71/aq/out/soong/host/linux-x86/bin/zipsync -d /home/iodine71/aq/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars -l /home/iodine71/aq/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars/list -f "*.java"  && /home/iodine71/aq/out/soong/host/linux-x86/bin/soong_javac_wrapper prebuilts/jdk/jdk9/linux-x86/bin/javac -J-Xmx2048M -Xmaxerrs 9999999 -encoding UTF-8 -sourcepath "" -g -XDskipDuplicateBridges=true -XDstringConcat=inline  -bootclasspath /home/iodine71/aq/out/soong/.intermediates/libcore/core-oj/android_common/turbine-combined/core-oj.jar:/home/iodine71/aq/out/soong/.intermediates/libcore/core-libart/android_common/turbine-combined/core-libart.jar -classpath /home/iodine71/aq/out/soong/.intermediates/frameworks/base/ext/android_common/turbine-combined/ext.jar:/home/iodine71/aq/out/soong/.intermediates/frameworks/base/framework/android_common/turbine-combined/framework.jar:/home/iodine71/aq/out/soong/.intermediates/external/okhttp/okhttp/android_common/turbine-jarjar/okhttp.jar:/home/iodine71/aq/out/soong/.intermediates/frameworks/base/services/net/services.net/android_common/turbine-combined/services.net.jar:/home/iodine71/aq/out/soong/.intermediates/hardware/interfaces/light/2.0/android.hardware.light-V2.0-java/android_common/turbine-combined/android.hardware.light-V2.0-java.jar:/home/iodine71/aq/out/soong/.intermediates/hardware/interfaces/power/1.0/android.hardware.power-V1.0-java/android_common/turbine-combined/android.hardware.power-V1.0-java.jar:/home/iodine71/aq/out/soong/.intermediates/hardware/interfaces/tv/cec/1.0/android.hardware.tv.cec-V1.0-java/android_common/turbine-combined/android.hardware.tv.cec-V1.0-java.jar:/home/iodine71/aq/out/soong/.intermediates/system/libhidl/transport/manager/1.0/android.hidl.manager-V1.0-java/android_common/turbine-combined/android.hidl.manager-V1.0-java.jar:/home/iodine71/aq/out/soong/.intermediates/system/timezone/distro/core/time_zone_distro/android_common/turbine-combined/time_zone_distro.jar:/home/iodine71/aq/out/soong/.intermediates/system/timezone/distro/installer/time_zone_distro_installer/android_common/turbine-combined/time_zone_distro_installer.jar:/home/iodine71/aq/out/soong/.intermediates/hardware/interfaces/authsecret/1.0/android.hardware.authsecret-V1.0-java/android_common/turbine-combined/android.hardware.authsecret-V1.0-java.jar:/home/iodine71/aq/out/soong/.intermediates/hardware/interfaces/broadcastradio/2.0/android.hardware.broadcastradio-V2.0-java/android_common/turbine-combined/android.hardware.broadcastradio-V2.0-java.jar:/home/iodine71/aq/out/soong/.intermediates/hardware/interfaces/health/1.0/android.hardware.health-V1.0-java/android_common/turbine-combined/android.hardware.health-V1.0-java.jar:/home/iodine71/aq/out/soong/.intermediates/hardware/interfaces/health/2.0/android.hardware.health-V2.0-java/android_common/turbine-combined/android.hardware.health-V2.0-java.jar:/home/iodine71/aq/out/soong/.intermediates/hardware/interfaces/weaver/1.0/android.hardware.weaver-V1.0-java/android_common/turbine-combined/android.hardware.weaver-V1.0-java.jar:/home/iodine71/aq/out/soong/.intermediates/hardware/interfaces/biometrics/fingerprint/2.1/android.hardware.biometrics.fingerprint-V2.1-java/android_common/turbine-combined/android.hardware.biometrics.fingerprint-V2.1-java.jar:/home/iodine71/aq/out/soong/.intermediates/hardware/interfaces/oemlock/1.0/android.hardware.oemlock-V1.0-java/android_common/turbine-combined/android.hardware.oemlock-V1.0-java.jar:/home/iodine71/aq/out/soong/.intermediates/hardware/interfaces/tetheroffload/control/1.0/android.hardware.tetheroffload.control-V1.0-java/android_common/turbine-combined/android.hardware.tetheroffload.control-V1.0-java.jar:/home/iodine71/aq/out/soong/.intermediates/hardware/interfaces/vibrator/1.0/android.hardware.vibrator-V1.0-java/android_common/turbine-combined/android.hardware.vibrator-V1.0-java.jar:/home/iodine71/aq/out/soong/.intermediates/hardware/interfaces/configstore/1.0/android.hardware.configstore-V1.0-java/android_common/turbine-combined/android.hardware.configstore-V1.0-java.jar:/home/iodine71/aq/out/soong/.intermediates/hardware/interfaces/contexthub/1.0/android.hardware.contexthub-V1.0-java/android_common/turbine-combined/android.hardware.contexthub-V1.0-java.jar:/home/iodine71/aq/out/soong/.intermediates/hardware/aquarios/interfaces/biometrics/fingerprint/inscreen/1.0/vendor.lineage.biometrics.fingerprint.inscreen-V1.0-java/android_common/turbine-combined/vendor.lineage.biometrics.fingerprint.inscreen-V1.0-java.jar -source 1.8 -target 1.8 -d /home/iodine71/aq/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes -s /home/iodine71/aq/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/anno @/home/iodine71/aq/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/services.core.unboosted.jar.rsp @/home/iodine71/aq/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars/list && /home/iodine71/aq/out/soong/host/linux-x86/bin/soong_zip -jar -o /home/iodine71/aq/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/services.core.unboosted.jar -C /home/iodine71/aq/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes -D /home/iodine71/aq/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes
frameworks/base/services/core/java/com/android/server/StorageManagerService.java:2313: error: method fdeChangePassword in interface IVold cannot be applied to given types;
            mVold.fdeChangePassword(type, password);
                 ^
  required: int,String,String
  found: int,String
  reason: actual and formal argument lists differ in length
1 error
[ 55% 432/784] -e  \033[0m

**Comment by Ingvarr71** [comment]
What is the reason for this?

**Comment by rc420head** [comment]
What device?

**Comment by Ingvarr71** [comment]
Xiaomi Redmi Note 6 Pro

**Comment by rc420head** [comment]
You need to use the x-ng branch and it's not ready yet

**Comment by Ingvarr71** [comment]
I would like to build android 9

**Comment by rc420head** [comment]
Oh OK try the a9-caf branch

**Comment by rc420head** [comment]
You know what, I forgot you need to "repopick -t gzud" that is if you are
on the a9-caf branch

**Comment by rc420head** [comment]
Also go here for faster/better help
https://t.me/joinchat/GbmcoEYGhR0N3NW3Tt4EUg

**Comment by Ingvarr71** [comment]
I use a branch a9-caf

**Comment by Ingvarr71** [comment]
"repopick -t gzud" this is a team?

**Comment by anayw2001** [comment]
@Ingvarr71 No

**Comment by rc420head** [comment]
@Ingvarr71
